name: protein-search
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - numpy==2.4.*
      - pandas==3.0.*
      - scipy==1.17.*
      - scikit-learn==1.8.*
      - matplotlib==3.10.*
      - seaborn==0.13.*
      - umap-learn==0.5.*
      - hdbscan==0.8.*
      - biopython==1.87
      - fair-esm==2.0.0
      - torch==2.11.*
      - requests==2.33.*
      - tqdm==4.67.*
      - jupyter
      - notebook